//
// File generated by HDevelop for HALCON/.NET (C#) Version 22.11.2.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_ImageZoomed;

    // Local control variables 

    HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_ImageZoomed);
    //* 关闭窗口
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.CloseWindow(HDevWindowStack.Pop());
    }
    //* 读取图像
    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, "images/4-1.png");

    //* 把一个图像进行缩放(处理图片比较大的情况下)
    ho_ImageZoomed.Dispose();
    HOperatorSet.ZoomImageFactor(ho_Image, out ho_ImageZoomed, 0.5, 0.5, "constant");

    //* 获取图像的尺寸
    hv_Width.Dispose();hv_Height.Dispose();
    HOperatorSet.GetImageSize(ho_ImageZoomed, out hv_Width, out hv_Height);
    ho_Image.Dispose();
    ho_ImageZoomed.Dispose();

    hv_Width.Dispose();
    hv_Height.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

